### ISSUE TITLE
Request: Method for refreshing the saved field

### ISSUE THREAD

**Issue by jacklinke** [schinckel/django-shared-property#1]
* Django Shared Property version: latest
* Python version: 3
* Operating System: Any

### Description

@schinckel awesome package. Just wondering if there is a good method for 'refreshing' the saved field if the fields it depend on change - even if this just means running a function or django admin command to process this change manually?

I looked through the source a bit, but I'm afraid I'm not comfortable enough with custom fields to propose a solution myself.

Any direction for how to approach this would be appreciated.

**Comment by schinckel** [comment]
Oh, the way it works is that you don't need to "refresh" the saved field - it converts the expression into python code that runs each time you access it (ie, a property).

If the data underneath changes - ie, there are database changes that your model instance does not know about, then you just need to reload the model data. (`instance.refresh_from_db()`, which will update those changed fields).

And since everything is dynamic, it doesn't write any of this data to the database. You can create an index to improve performance (I'm working on making that more automatic), and if the field definitions change (which is actually what I think you mean by this question), then you'd need to update that index in a migration.
